### PR TITLE
Wrapper changes, new endpoint parallelisation

### PR DESCRIPTION
**Pull request by Varunram**

### CODE REVIEW

**Comment by AliMeer** [comment]
@Varunram 

**Request:**

```
{
    "External": [
        "2N4nnERmW9yAVjKvSLWjSGSgPgt5jwxVeQX",
        "2MvYxep9EhaK7KPPoH1RVaR6vA983RFS5Pk",
        "2NEXSh8fvbqNAzSPpsiSfwM8GV7Xftw8fYA",
        "2N5vB7tzmZeeHe2r69emYXKAmxTsi6rHp4P",
        "2N4oQ559Xs1FThQh4Zpbhu66ie8EEDT22wu",
        "2Mx5hGQvC3htwaWQ5fssKThzZnWcYSP36CG",
        "2N67ZRtpgjqfSwsasHhzJwQVAbFYHtBLaw1",
        "2N3ZL4KVPHRYjSkTew1bbuFfySbrhkfgt4F",
        "2N3wZ3h5HFWSoboLXTAeJ22Y2RNSwB8Zjux",
        "2N31wiRjQbLmGBT6qBMbjUEFejcMbuBtQZP",
        "2N4v4vQYfw94vpTmAvV6sKS7MrUdVJKE1gz",
        "2N9CVHUxvKMjmmQfwwRt8XaQLiV3SVB1dsY",
        "2N18boX529enPKKb7N4FCeSp6iJhctPzkp8",
        "2Mtbmj22YmobVchNe2E1c79H2sZyd6v5c1b",
        "2N6tRJLz6mnko3evVEPwBn7Povyf1ub3GcR",
        "2N44RHE4Y8WHRdG6Ru3gn5cMRuRCX3PhFKu",
        "2N3uzn5zV4Lz1zFzGwWv3cnz2oCrfAtGw2u",
        "2MyTm8U6FDuXp3vsheuobXdqqhhTDeMAbQ9",
        "2N1B8pEi5YjFG95LbRDifMoN4kFPstRe9uA",
        "2NDQC9AFD5Aifpw9QG4ixQK8Pbux9uJH8MB",
        "2MvKvgwwNBsm3jET7X1KiN3cio6WK9tSq6Z"
    ],
    "Internal": [
        "2MsY3Vgw2zi26jXe6hJHnyAa4Yy9uJaDrGr",
        "2N5UGsUwneuMSMmEedQzV7mhHoXnDJQChxe",
        "2NF5FpJKMGu7ioFQoVT9tuXZf223fztU9xy",
        "2MwmJU8jGhMDoxbpN23i3s4AaRmWBmpnoet",
        "2N6yvGBkjGw1KFwC9i8mQDpSebPAX3ppEsf",
        "2NDESPQM3jdGhHjkbySW6jhnn3h5LHjAfUV",
        "2N6QVeEbx5NddgwkWmTYXqTNoWHReZ24BQh",
        "2MyN32X81TqCoVMJrHVCQh5h9XiuXW2mjc5",
        "2MycSJrwjcPyPq1qABrjDzPVAcGWc2rq3SW",
        "2Mwj5S1JriSfRqVjg5Md6JCBnNwb5SLjniz",
        "2Myx22KQXamdZm2Aosb2UBEbJL8pRq3LZHG",
        "2N1EJd4NM75QBSTCKdRfu8G5pKr6z1eMbMH",
        "2Mx5QB5Vi9RnyFPTEcnGBriDXH8VJ66fnWH",
        "2MtLkhCykvme27fWgHEdpghTWCfwg1cG15L",
        "2N2gw2LEtbp6g8Q1pUtVZh4vp1uHCgQ2iBj",
        "2NGRobUe74kwYHKnUsEvxneEPN1miNpmSax",
        "2N7p9p69YB3MySBjbfyqBeckqvBZaPKy5Lp",
        "2MxyKYCKGrowvsdwX9HY55MYeUsSp7MMaP2",
        "2MwDUukxhwJCdguQjCUFVa8Yv5PKD14qFzc",
        "2N6JGAyvb4X7vULQ6XpG3LfnCMRcb2bJt8d",
        "2ND133Hhutdnf2oTz9Dbe95RKzW8sej5wrt"
    ]
}
```

**Response:**   

```
{
    "Utxos": [
        [
            {
                "txid": "c079051ceab7ada9f442eb84f9a81f40024cc6615d7850d6a91d9fc8ba7be8ef",
                "vout": 0,
                "status": {
                    "confirmed": true,
                    "block_height": 1891022,
                    "block_hash": "0000000028158433804c7251d30f39ce807fda38f97a4dc457ed7a0054d6fcc2",
                    "block_time": 1604946028
                },
                "value": 2000,
                "Address": "2MvYxep9EhaK7KPPoH1RVaR6vA983RFS5Pk"
            }
        ],
        [
            {
                "txid": "b3cacc1481c8b6ad95d6f0240e1d5c88327b4164b3b25a793150b6349a474062",
                "vout": 0,
                "status": {
                    "confirmed": true,
                    "block_height": 1891019,
                    "block_hash": "000000000000005c86c876d965392eaf3891a1d00804adc67796cb94e92b89b1",
                    "block_time": 1604943316
                },
                "value": 8348,
                "Address": "2MsY3Vgw2zi26jXe6hJHnyAa4Yy9uJaDrGr"
            }
        ]
    ],
    "Txs": [
        {
            "TotalTransactions": 2,
            "ConfirmedTransactions": 1,
            "UnconfirmedTransactions": 0,
            "Transactions": [
                {
                    "txid": "b3cacc1481c8b6ad95d6f0240e1d5c88327b4164b3b25a793150b6349a474062",
                    "version": 2,
                    "locktime": 0,
                    "vin": null,
                    "Vout": null,
                    "size": 248,
                    "weight": 662,
                    "fee": 452,
                    "Status": {
                        "confirmed": true,
                        "block_height": 1891019,
                        "block_hash": "000000000000005c86c876d965392eaf3891a1d00804adc67796cb94e92b89b1",
                        "block_time": 1604943316
                    },
                    "NumberofConfirmations": 4,
                    "TransactionType": "Sent",
                    "SenderAddresses": null,
                    "SentAmount": 0,
                    "ReceivedAmount": 0,
                    "Amount": 8800,
                    "RecipientAddresses": [
                        "2MsY3Vgw2zi26jXe6hJHnyAa4Yy9uJaDrGr"
                    ]
                },
                {
                    "txid": "dbe668a78c1252f48b99114c17a6cd4d2ba0efedbff1193dd579298bd7fb95d9",
                    "version": 2,
                    "locktime": 0,
                    "vin": null,
                    "Vout": null,
                    "size": 247,
                    "weight": 661,
                    "fee": 1130,
                    "Status": {
                        "confirmed": true,
                        "block_height": 1891019,
                        "block_hash": "000000000000005c86c876d965392eaf3891a1d00804adc67796cb94e92b89b1",
                        "block_time": 1604943316
                    },
                    "NumberofConfirmations": 4,
                    "TransactionType": "Self",
                    "SenderAddresses": [
                        "2N1TSArdd2pt9RoqE3LXY55ixpRE9e5aot8"
                    ],
                    "SentAmount": 9967730468,
                    "ReceivedAmount": 9967729338,
                    "Amount": 1130,
                    "RecipientAddresses": [
                        "2N1TSArdd2pt9RoqE3LXY55ixpRE9e5aot8",
                        "2N4nnERmW9yAVjKvSLWjSGSgPgt5jwxVeQX"
                    ]
                }
            ],
            "Address": "2N4nnERmW9yAVjKvSLWjSGSgPgt5jwxVeQX"
        },
        {
            "TotalTransactions": 1,
            "ConfirmedTransactions": 1,
            "UnconfirmedTransactions": 0,
            "Transactions": [
                {
                    "txid": "c079051ceab7ada9f442eb84f9a81f40024cc6615d7850d6a91d9fc8ba7be8ef",
                    "version": 2,
                    "locktime": 0,
                    "vin": null,
                    "Vout": null,
                    "size": 248,
                    "weight": 662,
                    "fee": 226,
                    "Status": {
                        "confirmed": true,
                        "block_height": 1891022,
                        "block_hash": "0000000028158433804c7251d30f39ce807fda38f97a4dc457ed7a0054d6fcc2",
                        "block_time": 1604946028
                    },
                    "NumberofConfirmations": 1,
                    "TransactionType": "Self",
                    "SenderAddresses": [
                        "2My5TGmrn3GBurt3dzaQQxqiw84uPRK8Bc4"
                    ],
                    "SentAmount": 8000,
                    "ReceivedAmount": 7774,
                    "Amount": 226,
                    "RecipientAddresses": [
                        "2N7MCfgP1H1V7GWHSBkm5JGcFBkYSjYohaV"
                    ]
                }
            ],
            "Address": "2MvYxep9EhaK7KPPoH1RVaR6vA983RFS5Pk"
        },
        {
            "TotalTransactions": 1,
            "ConfirmedTransactions": 1,
            "UnconfirmedTransactions": 0,
            "Transactions": [
                {
                    "txid": "b3cacc1481c8b6ad95d6f0240e1d5c88327b4164b3b25a793150b6349a474062",
                    "version": 2,
                    "locktime": 0,
                    "vin": null,
                    "Vout": null,
                    "size": 248,
                    "weight": 662,
                    "fee": 452,
                    "Status": {
                        "confirmed": true,
                        "block_height": 1891019,
                        "block_hash": "000000000000005c86c876d965392eaf3891a1d00804adc67796cb94e92b89b1",
                        "block_time": 1604943316
                    },
                    "NumberofConfirmations": 4,
                    "TransactionType": "Sent",
                    "SenderAddresses": null,
                    "SentAmount": 0,
                    "ReceivedAmount": 0,
                    "Amount": 8800,
                    "RecipientAddresses": [
                        "2MsY3Vgw2zi26jXe6hJHnyAa4Yy9uJaDrGr"
                    ]
                }
            ],
            "Address": "2MsY3Vgw2zi26jXe6hJHnyAa4Yy9uJaDrGr"
        }
    ]
}
```


1. This should return 2 UTXOs which is correct.

2. In the `Txs` data , the first transaction txid  b3cacc1481c8b6ad95d6f0240e1d5c88327b4164b3b25a793150b6349a474062  sent 1200 t-sats to another address: 2N2GEcwoRXmzPVjcbj2eBkYA4qH5jfQKxzZ  and the fee for this was 452  This can be confirmed here:   https://www.blockchain.com/btc-testnet/tx/b3cacc1481c8b6ad95d6f0240e1d5c88327b4164b3b25a793150b6349a474062
 
However the `Txs` in the response has this transaction mentioned twice with missing data for SentAmount, SenderAddresses and RecievedAmount: 

```

"TransactionType": "Sent",
"SenderAddresses": null,
"SentAmount": 0,
"ReceivedAmount": 0,
"Amount": 8800,
"RecipientAddresses": [
       "2MsY3Vgw2zi26jXe6hJHnyAa4Yy9uJaDrGr"
]

```

**_1- So What I can conclude is that the first address in the request is perhaps is being treated differently and its Txs are not being added to the response correctly.

Could it be that we are starting from index 1 and not 0 ? 😊

2- The other issue is that we are showing the fee recipients address instead of the users address._**  Correction, not the fee recipient address but the change address or the internal address.

**Comment by AliMeer** [comment]
Here is another one:

**Request**:

```
{
    "External": [
        "2N2GEcwoRXmzPVjcbj2eBkYA4qH5jfQKxzZ",
        "2MuhYp4C2FWLn1kn9cREK4iTgH1x3ZXCZ3x",
        "2MuPwckCihX8QHzUXXB8wBgR3AsUrPcd49B",
        "2N7fZP612ew9MKU649oyvw2DgfJRHhaLFz6",
        "2N3HWZ9omkhwpWoFDnu6hJ7bybbsf36mq6G",
        "2N4GfMvEY3TiY6u44c1ePzbMNfPKsUZ6ZdD",
        "2NG17mbLesbmy99tNfrv1kn8pAafuXvfPew",
        "2N8MF9tpzjtUT7g1z1Tdh2ExJWSfqyQwp8E",
        "2NCxCUaGobYf7V1zFQLFdSYF8T4NsMrBgrM",
        "2NA4Um9BQ9HttbYZRgvQbHTYRciZQssWZTu",
        "2NFN287kXPND8bmGRBoTS7H7m7EHV425w2C",
        "2MycgHbX1WzMo926qoNyuURLdAEzmiPm9TV",
        "2N6gxYWsX7WNwcjNDmPuBSFJkztTon3fy8c",
        "2Mw2kc3kRKChkpRBhmnjApDEFBHKRzgJvJb",
        "2N7C2rtf2VJ8Pm8oEyB2YnoyU7NLzhkHaXS",
        "2NF61q5giKGnxuN36XwjS9jGzC7ZMyHUTun",
        "2ND7qXvQEvirupnCqaXpnJNaW4g3dY2fUQk",
        "2MyJvkwhQE8FuEsiVWeDriMcbYtEvVZD6CM",
        "2N4H9c7V3vd79ptSUjbrkRwTmWZohG3XnP9",
        "2N5isj1bpLH98Eh5VYJBBc4LQXt5PpRZnpn",
        "2NCipffKgQjDgw1G1Xy2iEaLW18kgtKTtdv"
    ],
    "Internal": [
        "2N4WNzF4iEHVdj4Czb18kW8DYPo43LZoWzr",
        "2Mur1CZM7pad8DFxyKYLsTPKhqYRdsYqjNY",
        "2NFyBFtXb3G9HiRJDmrkXPQbfq1WigCEKUm",
        "2MwWLLE1kP9dRnRaLAN6cW8fsGDVsvx28e7",
        "2N9HqHwXuBb94WxSD7GcpCX3sYqA8UnUv4Q",
        "2NB2bUtspJW3hPVt8Cg9A58oa4BvaaSCivf",
        "2N7msVadiVty6ZPPia7AbWz1bwZH7gc64aD",
        "2N6tTW729xdGk7VBDgdQVDnkAnSuefNXuNE",
        "2N4Xd54KQ1jtfPue5hZBYweqJqdRukrhtwi",
        "2MshUd5XkTRhMKBdcS4aLbJm1zULQUMm55L",
        "2NFdEAJJSLmH4F3MK94oEN7PpiYH7a4v5w8",
        "2NEHGaqcAzLfDmHZELYu51B4FpwiEo23hVh",
        "2NENHnVBJCB74YNRvzP3qiJyuUnYCnW21Ss",
        "2NC8BiPZwxkV79A3JSEHKCny6nNueyp76dG",
        "2NETbybHut128zm5aC6jHHyG7DbFps3oJCg",
        "2MtbdoCfihJkzaeuuHPHNn7BFGJtfgNZ8aV",
        "2NFichqqgnFQyvske8wWZMbTdVXXrCvPbtk",
        "2N8KjkNKd3PueYo1JVLX2dPMb2jXEgabNTF",
        "2N1rZkNhvQCizhYPunWSbaSj4RaQrFgvxUU",
        "2NGEzUADAoynjnFhSRDhArq6EUZuauUhurZ"
    ]
}
```

**Response**
```

{
    "Utxos": [
        [
            {
                "txid": "b3cacc1481c8b6ad95d6f0240e1d5c88327b4164b3b25a793150b6349a474062",
                "vout": 1,
                "status": {
                    "confirmed": true,
                    "block_height": 1891019,
                    "block_hash": "000000000000005c86c876d965392eaf3891a1d00804adc67796cb94e92b89b1",
                    "block_time": 1604943316
                },
                "value": 1200,
                "Address": "2N2GEcwoRXmzPVjcbj2eBkYA4qH5jfQKxzZ"
            }
        ]
    ],
    "Txs": [
        {
            "TotalTransactions": 1,
            "ConfirmedTransactions": 1,
            "UnconfirmedTransactions": 0,
            "Transactions": [
                {
                    "txid": "b3cacc1481c8b6ad95d6f0240e1d5c88327b4164b3b25a793150b6349a474062",
                    "version": 2,
                    "locktime": 0,
                    "vin": null,
                    "Vout": null,
                    "size": 248,
                    "weight": 662,
                    "fee": 452,
                    "Status": {
                        "confirmed": true,
                        "block_height": 1891019,
                        "block_hash": "000000000000005c86c876d965392eaf3891a1d00804adc67796cb94e92b89b1",
                        "block_time": 1604943316
                    },
                    "NumberofConfirmations": 12,
                    "TransactionType": "Sent",
                    "SenderAddresses": null,
                    "SentAmount": 0,
                    "ReceivedAmount": 0,
                    "Amount": 8800,
                    "RecipientAddresses": [
                        "2MsY3Vgw2zi26jXe6hJHnyAa4Yy9uJaDrGr"
                    ]
                }
            ],
            "Address": "2N2GEcwoRXmzPVjcbj2eBkYA4qH5jfQKxzZ"
        }
    ]
}
```

This account is a testnet regular account.

It received 1200 t-sats with 452 fees on first external address 2N2GEcwoRXmzPVjcbj2eBkYA4qH5jfQKxzZ from 2N4nnERmW9yAVjKvSLWjSGSgPgt5jwxVeQX

The Txns object is showing on transaction which is correct, however the data is as follows:
 ```
"TransactionType": "Sent",
"SenderAddresses": null,
"SentAmount": 0,
 "ReceivedAmount": 0,
 "Amount": 8800,
"RecipientAddresses": [
                        "2MsY3Vgw2zi26jXe6hJHnyAa4Yy9uJaDrGr"
                    ]
```

**_1- We are showing the fee recipients address instead of the users address._** Correction, not the fee recipient's address but the senders change address. The txid shown is the output which went back to the sender.

**Comment by Parsh** [comment]
There's some sort of err in the categorisation function that the wrapper is performing, it is not taking the internal address as it's own and therefore computing a wrong sent amount as can be seen in the snippets below.

Request object: 
````
{
    "External": [
        "2NCJVF5nhtqXYV9i6RJAYLgxTy4gd1ZwBzy",
        "2NE7Bv5wUGytjbzq4uidoCCeJNbknZYSWjS"
    ],
    "Internal": [
        "2N3N1E5Z45iCg438H9rCYBV9ex5TNMt9PHA",
        "2N4mX6h4dT4XhDfDP4ADN9U5LvH3C6sn46U"
    ]
}
````


Response from new wrapper end-point:
````
{
    "Utxos": [
        [
            {
                "txid": "b2b9e13f3c6170b6322985e243e6e1b6a589465ddac0c41d53186b90165ee052",
                "vout": 1,
                "status": {
                    "confirmed": false,
                    "block_height": 0,
                    "block_hash": "",
                    "block_time": 0
                },
                "value": 7274,
                "Address": "2N3N1E5Z45iCg438H9rCYBV9ex5TNMt9PHA"
            }
        ]
    ],
    "Txs": [
        {
            "TotalTransactions": 2,
            "ConfirmedTransactions": 0,
            "UnconfirmedTransactions": 1,
            "Transactions": [
                {
                    "txid": "ecbe81676a2fea544fe635506058f9ad8c58dc94ae69e3de841895dedff12705",
                    "version": 2,
                    "locktime": 0,
                    "vin": null,
                    "Vout": null,
                    "size": 247,
                    "weight": 661,
                    "fee": 1130,
                    "Status": {
                        "confirmed": false,
                        "block_height": 0,
                        "block_hash": "",
                        "block_time": 0
                    },
                    "NumberofConfirmations": 0,
                    "TransactionType": "Received",
                    "SenderAddresses": [
                        "2N1TSArdd2pt9RoqE3LXY55ixpRE9e5aot8"
                    ],
                    "SentAmount": 0,
                    "ReceivedAmount": 0,
                    "Amount": 10000,
                    "RecipientAddresses": null
                },
                {
                    "txid": "b2b9e13f3c6170b6322985e243e6e1b6a589465ddac0c41d53186b90165ee052",
                    "version": 2,
                    "locktime": 0,
                    "vin": null,
                    "Vout": null,
                    "size": 248,
                    "weight": 662,
                    "fee": 226,
                    "Status": {
                        "confirmed": false,
                        "block_height": 0,
                        "block_hash": "",
                        "block_time": 0
                    },
                    "NumberofConfirmations": 0,
                    "TransactionType": "Sent",
                    "SenderAddresses": null,
                    "SentAmount": 0,
                    "ReceivedAmount": 0,
                    "Amount": 10000,
                    "RecipientAddresses": [
                        "2N1TSArdd2pt9RoqE3LXY55ixpRE9e5aot8",
                        "2N3N1E5Z45iCg438H9rCYBV9ex5TNMt9PHA"
                    ]
                }
            ],
            "Address": "2NCJVF5nhtqXYV9i6RJAYLgxTy4gd1ZwBzy"
        },
        {
            "TotalTransactions": 1,
            "ConfirmedTransactions": 0,
            "UnconfirmedTransactions": 1,
            "Transactions": [
                {
                    "txid": "b2b9e13f3c6170b6322985e243e6e1b6a589465ddac0c41d53186b90165ee052",
                    "version": 2,
                    "locktime": 0,
                    "vin": null,
                    "Vout": null,
                    "size": 248,
                    "weight": 662,
                    "fee": 226,
                    "Status": {
                        "confirmed": false,
                        "block_height": 0,
                        "block_hash": "",
                        "block_time": 0
                    },
                    "NumberofConfirmations": 0,
                    "TransactionType": "Sent",
                    "SenderAddresses": null,
                    "SentAmount": 0,
                    "ReceivedAmount": 0,
                    "Amount": 10000,
                    "RecipientAddresses": [
                        "2N1TSArdd2pt9RoqE3LXY55ixpRE9e5aot8",
                        "2N3N1E5Z45iCg438H9rCYBV9ex5TNMt9PHA"
                    ]
                }
            ],
            "Address": "2N3N1E5Z45iCg438H9rCYBV9ex5TNMt9PHA"
        }
    ]
}



Response from in-app processing(current dev):
{
    "transaction": {
        "totalTransactions": 3,
        "confirmedTransactions": 2,
        "unconfirmedTransactions": 0,
        "transactionDetails": [
            {
                "txid": "b2b9e13f3c6170b6322985e243e6e1b6a589465ddac0c41d53186b90165ee052",
                "confirmations": 2,
                "status": "Confirmed",
                "fee": 226,
                "date": "Thu, 12 Nov 2020 11:04:46 GMT",
                "transactionType": "Sent",
                "amount": 2726,
                "accountType": "Test Account",
                "recipientAddresses": [
                    "2N1TSArdd2pt9RoqE3LXY55ixpRE9e5aot8"
                ],
                "blockTime": 1605179086
            },
            {
                "txid": "ecbe81676a2fea544fe635506058f9ad8c58dc94ae69e3de841895dedff12705",
                "confirmations": 2,
                "status": "Confirmed",
                "fee": 1130,
                "date": "Thu, 12 Nov 2020 11:04:46 GMT",
                "transactionType": "Received",
                "amount": 10000,
                "accountType": "Test Account",
                "senderAddresses": [
                    "2N1TSArdd2pt9RoqE3LXY55ixpRE9e5aot8"
                ],
                "blockTime": 1605179086
            }
        ]
    }
}
  

Txn with the txid: **b2b9e13f3c6170b6322985e243e6e1b6a589465ddac0c41d53186b90165ee052** has a wrong sent
 amoutn because it is considering the internal address(to which change is sent) as a recipient address.

https://www.blockchain.com/btc-testnet/tx/b2b9e13f3c6170b6322985e243e6e1b6a589465ddac0c41d53186b90165ee052

**Comment by Varunram** [comment]
Fixed, the bug was in sort.SearchStrings (headbutts into the wall nearby)

**Review by AliMeer — APPROVED** [review]

**Pull request merged**
